In [ ]:
class Car:
  def __init__(self, make, model="sedan"):
    self.make = make
    self.model = model
  def start_engine(self):
    print("Hello")

my_car=Car("toyota")
print(my_car.model)
my_car.start_engine()

sedan
Hello

In [ ]:
import pandas as pd

# Series

In [ ]:
x = pd.Series([6,3,4,6])
print(x)

0    6
1    3
2    4
3    6
dtype: int64

## Mengubah index

In [ ]:
# Cara 1:

x.index = ['a', 'b', 'c', 'd']
print(x)

a    6
b    3
c    4
d    6
dtype: int64

In [ ]:
# Cara 2:

x = pd.Series([6,3,4,6], index=['a', 'c', 'b', 'd'])
print(x)

a    6
c    3
b    4
d    6
dtype: int64

# Dataframe

## Membuat dataframe

In [ ]:
df = pd.DataFrame({'tipe_int': [50, 21], 'tipe_string': ['a', 'b']})
df

   tipe_int tipe_string
0        50           a
1        21           b

## Membuat dataframe dari List

In [ ]:
# Data dalam bentuk list untuk setiap kolom
nama = ['Alice', 'Bob', 'Charlie', 'David']
usia = [25, 30, 35, 40]
kota = ['New York', 'Los Angeles', 'Chicago', 'Houston']

# Membuat DataFrame dari list
df = pd.DataFrame({'Nama': nama, 'Usia': usia, 'Kota': kota})

# Menampilkan DataFrame
df

      Nama  Usia         Kota
0    Alice    25     New York
1      Bob    30  Los Angeles
2  Charlie    35      Chicago
3    David    40      Houston

## Membuat dataframe dari Dictionary

In [ ]:
data = {'Nama': ['Alice', 'Bob', 'Charlie', 'David'],
        'Usia': [25, 30, 35, 40]}

df = pd.DataFrame(data)

print(df)

      Nama  Usia
0    Alice    25
1      Bob    30
2  Charlie    35
3    David    40

## Membaca file

In [ ]:
df = pd.read_excel('/content/Book1.xlsx', sheet_name='Sheet1')
df

    Nama  Umur         Kota
0   Andi    15      Bandung
1  Mawar    12      Jakarta
2   Doni    49         Solo
3   Siti    32  Banjarmasin

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/SanberCode X ITB/File Handling/file_02.csv')
df

   NO  NAMA  NILAI
0   1  Budi     95

## Menampilkan data

In [ ]:
import random

# Membuat data acak untuk contoh DataFrame
data = {
    'Nama': [f'Orang-{i}' for i in range(1, 21)],
    'Usia': [random.randint(18, 60) for _ in range(20)],
    'Kota': [random.choice(['Jakarta', 'Surabaya', 'Bandung', 'Medan', 'Semarang']) for _ in range(20)],
    'Pekerjaan': [random.choice(['Guru', 'Dokter', 'Insinyur', 'Pengacara', 'Desainer']) for _ in range(20)],
    'Pendapatan': [random.randint(2000000, 16000000) for _ in range(20)]
}

# Membuat DataFrame dari data
df = pd.DataFrame(data)

# Menampilkan DataFrame
print(df)

        Nama  Usia      Kota  Pekerjaan  Pendapatan
0    Orang-1    54  Semarang  Pengacara    13466374
1    Orang-2    56   Jakarta   Desainer     8217531
2    Orang-3    45  Surabaya  Pengacara     8715954
3    Orang-4    40  Semarang   Insinyur     7823994
4    Orang-5    59   Bandung  Pengacara     7809826
5    Orang-6    44  Surabaya  Pengacara     4601636
6    Orang-7    49     Medan       Guru     7669934
7    Orang-8    59     Medan   Insinyur     7738589
8    Orang-9    54  Semarang       Guru     9840747
9   Orang-10    55     Medan   Desainer    13265051
10  Orang-11    41  Surabaya   Desainer    12536539
11  Orang-12    40  Semarang   Desainer     9397350
12  Orang-13    44   Bandung  Pengacara     6520312
13  Orang-14    26  Surabaya     Dokter     7704121
14  Orang-15    53   Jakarta     Dokter     3176794
15  Orang-16    58  Surabaya       Guru     4840649
16  Orang-17    55   Jakarta   Desainer    14341085
17  Orang-18    44   Bandung     Dokter     2683451
18  Orang-19    22  Semarang   Insinyur    15820294
19  Orang-20    31  Surabaya  Pengacara     8236828

## Melihat data pertama

In [ ]:
# Menampilkan 3 baris pertama
print(df.head())

      Nama  Usia      Kota Pekerjaan  Pendapatan
0  Orang-1    42   Bandung  Insinyur    15178184
1  Orang-2    27  Semarang    Dokter    14447364
2  Orang-3    58  Surabaya      Guru     7092198
3  Orang-4    24  Semarang    Dokter     7106812
4  Orang-5    23   Jakarta      Guru     2568747

## Melihat data terakhir

In [ ]:
# Menampilkan 2 baris terakhir
print(df.tail())

        Nama  Usia      Kota  Pekerjaan  Pendapatan
15  Orang-16    29   Jakarta  Pengacara     5227941
16  Orang-17    58  Semarang       Guru     8377913
17  Orang-18    20  Semarang   Desainer     8396137
18  Orang-19    19  Semarang   Desainer    14759622
19  Orang-20    39  Surabaya     Dokter    14167809

## Mengetahui info dasar

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Nama        20 non-null     object
 1   Usia        20 non-null     int64
 2   Kota        20 non-null     object
 3   Pekerjaan   20 non-null     object
 4   Pendapatan  20 non-null     int64
dtypes: int64(2), object(3)
memory usage: 928.0+ bytes

## Melihat data unik

In [ ]:
df.Kota.unique()

array(['Semarang', 'Jakarta', 'Surabaya', 'Bandung', 'Medan'],
      dtype=object)

## Menampilkan Statistika Deskriptif

In [ ]:
df.describe()

            Usia    Pendapatan
count  20.000000  2.000000e+01
mean   33.000000  8.889936e+06
std    12.830884  4.298726e+06
min    19.000000  2.145058e+06
25%    22.250000  5.609296e+06
50%    29.500000  8.098900e+06
75%    39.750000  1.318497e+07
max    58.000000  1.542884e+07

# Indexing dan Akses Data

## Series as Dictionary

In [ ]:
obj_series = pd.Series([1,2,3,4], index=['a','b','c','d'])
obj_series

a    1
b    2
c    3
d    4
dtype: int64

In [ ]:
#indexing key
obj_series.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [ ]:
#indexing value
obj_series.values

array([1, 2, 3, 4])

In [ ]:
#checking existing keys
'f' in obj_series

False

## Series as array

In [ ]:
# slicing dengan explicit index
obj_series['a']

1

In [ ]:
#slicing dengan implicit index
obj_series[:3]

a    1
b    2
c    3
dtype: int64

## Menggunakan .loc dan .iloc object series

In [ ]:
#.loc indexing
obj_series.loc['a':'c']

a    1
b    2
c    3
dtype: int64

In [ ]:
#.iloc indexing
obj_series.iloc[:3]

a    1
b    2
c    3
dtype: int64

## Indexing DataFrame

In [ ]:
df_ramen = pd.read_csv('/content/ramen-ratings.csv')
df_ramen.head()

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
0,2580,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN
1,2579,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1,NaN
2,2578,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN
4,2576,Ching's Secret,Singapore Curry,Pack,India,3.75,NaN

## Indexing operator as series

In [ ]:
df_ramen['Brand']

0            New Touch
1             Just Way
2               Nissin
3              Wei Lih
4       Ching's Secret
             ...
2575             Vifon
2576           Wai Wai
2577           Wai Wai
2578           Wai Wai
2579          Westbrae
Name: Brand, Length: 2580, dtype: object

## Indexing operator as dataframe

In [ ]:
df_ramen[['Brand']].head()

            Brand
0       New Touch
1        Just Way
2          Nissin
3         Wei Lih
4  Ching's Secret

## Indexing using attributes

In [ ]:
df_ramen.Brand

0            New Touch
1             Just Way
2               Nissin
3              Wei Lih
4       Ching's Secret
             ...
2575             Vifon
2576           Wai Wai
2577           Wai Wai
2578           Wai Wai
2579          Westbrae
Name: Brand, Length: 2580, dtype: object

## Indexing using .loc

In [ ]:
df_ramen.loc[4:10, ['Country', 'Stars']]

        Country Stars
4         India  3.75
5   South Korea  4.75
6         Japan     4
7         Japan  3.75
8         Japan  0.25
9     Singapore   2.5
10     Thailand     5

## Indexing using .iloc

In [ ]:
df_ramen.iloc[:, [1, 5]]

               Brand Stars
0          New Touch  3.75
1           Just Way     1
2             Nissin  2.25
3            Wei Lih  2.75
4     Ching's Secret  3.75
...              ...   ...
2575           Vifon   3.5
2576         Wai Wai     1
2577         Wai Wai     2
2578         Wai Wai     2
2579        Westbrae   0.5

[2580 rows x 2 columns]

# Filtering DataFrame with Boolean

In [ ]:
df = pd.read_csv('/content/titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Dari gambar dapat kita lihat bahwa data kita memiliki beberapa column seperti tentang status survived, tentang umur, tentang jenis kelamain, dan lain-lain. misalkan boss kita menyuruh kita untuk melakukan beberapa hal sebagai berikut :

1. Tunjukan kepada saya semua data orang-orang yang selamat!!
2. Tunjukan kepada saya semua data laki-laki yang selamat.
3. Tunjukan kepada saya semua data tentang perempuan yang tidak selamat di umur lebih dari 40 tahun atau kurang dari 20 tahun.

### 1. Data orang yang selamat

In [ ]:
# kondisi orang selamat
Survived = df["Survived"] == 1
Survived = df.Survived == 1

In [ ]:
df[Survived]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df[df.Survived==1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

### 2. Data laki-laki yang selamat

In [ ]:
# kondisi orang selamat
Survived = df.Survived == 1
# kondisi orang laki-laki
laki = df.Sex == 'male'

In [ ]:
df[(df.Survived == 1)&(df.Sex == 'male')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
36,37,1,3,"Mamee, Mr. Hanna",male,NaN,0,0,2677,7.2292,NaN,C
55,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S
...,...,...,...,...,...,...,...,...,...,...,...,...
838,839,1,3,"Chip, Mr. Chang",male,32.0,0,0,1601,56.4958,NaN,S
839,840,1,1,"Marechal, Mr. Pierre",male,NaN,0,0,11774,29.7000,C47,C
857,858,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,113055,26.5500,E17,S
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

### 3. Data perempuan yang tidak selamat di umur lebih dari 40 tahun atau kurang dari 20 tahun.

In [ ]:
# orang yang tidak selamat
not_survived = df.Survived == 0

# orang berjnis kelamin perempuan
perempuan = df.Sex == 'female'

# orang yang berumur lebih dari 40 tahun
lebih_40 = df.Age > 40

# orang yang berumur kurang dari 20 tahun
kurang_20 = df.Age < 20

In [ ]:
df[(df.Survived == 0)&(df.Sex == 'female')&((df.Age > 40) | (df.Age < 20))]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S
38,39,0,3,"Vander Planke, Miss. Augusta Maria",female,18.0,2,0,345764,18.0000,NaN,S
49,50,0,3,"Arnold-Franchi, Mrs. Josef (Josefine Franchi)",female,18.0,1,0,349237,17.8000,NaN,S
71,72,0,3,"Goodwin, Miss. Lillian Amy",female,16.0,5,2,CA 2144,46.9000,NaN,S
111,112,0,3,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C
114,115,0,3,"Attalah, Miss. Malake",female,17.0,0,0,2627,14.4583,NaN,C
119,120,0,3,"Andersson, Miss. Ellis Anna Maria",female,2.0,4,2,347082,31.2750,NaN,S
132,133,0,3,"Robins, Mrs. Alexander A (Grace Charity Laury)",female,47.0,1,0,A/5. 3337,14.5000,NaN,S
147,148,0,3,"Ford, Miss. Robina Maggie ""Ruby""",female,9.0,2,2,W./C. 6608,34.3750,NaN,S
167,168,0,3,"Skoog, Mrs. William (Anna Bernhardina Karlsson)",female,45.0,1,4,347088,27.9000,NaN,S
177,178,0,1,"Isham, Miss. Ann Elizabeth",female,50.0,0,0,PC 17595,28.7125,C49,C
205,206,0,3,"Strom, Miss. Telma Matilda",female,2.0,0,1,347054,10.4625,G6,S
254,255,0,3,"Rosblom, Mrs. Viktor (Helena Wilhelmina)",female,41.0,0,2,370129,20.2125,NaN,S
276,277,0,3,"Lindblom, Miss. Augusta Charlotta",female,45.0,0,0,347073,7.7500,NaN,S
297,298,0,1,"Allison, Miss. Helen Loraine",female,2.0,1,2,113781,151.5500,C22 C26,S
362,363,0,3,"Barbara, Mrs. (Catherine David)",female,45.0,0,1,2691,14.4542,NaN,C
374,375,0,3,"Palsson, Miss. Stina Viola",female,3.0,3,1,349909,21.0750,NaN,S
419,420,0,3,"Van Impe, Miss. Catharina",female,10.0,0,2,345773,24.1500,NaN,S
541,542,0,3,"Andersson, Miss. Ingeborg Constanzia",female,9.0,4,2,347082,31.2750,NaN,S
542,543,0,3,"Andersson, Miss. Sigrid Elisabeth",female,11.0,4,2,347082,31.2750,NaN,S
634,635,0,3,"Skoog, Miss. Mabel",female,9.0,3,2,347088,27.9000,NaN,S
638,639,0,3,"Panula, Mrs. Juha (Maria Emilia Ojala)",female,41.0,0,5,3101295,39.6875,NaN,S
642,643,0,3,"Skoog, Miss. Margit Elizabeth",female,2.0,3,2,347088,27.9000,NaN,S
654,655,0,3,"Hegarty, Miss. Hanora ""Nora""",female,18.0,0,0,365226,6.7500,NaN,Q
678,679,0,3,"Goodwin, Mrs. Frederick (Augusta Tyler)",female,43.0,1,6,CA 2144,46.9000,NaN,S
702,703,0,3,"Barbara, Miss. Saiide",female,18.0,0,1,2691,14.4542,NaN,C
736,737,0,3,"Ford, Mrs. Edward (Margaret Ann Watson)",female,48.0,1,3,W./C. 6608,34.3750,NaN,S
772,773,0,2,"Mack, Mrs. (Mary)",female,57.0,0,0,S.O./P.P. 3,10.5000,E77,S
807,808,0,3,"Pettersson, Miss. Ellen Natalia",female,18.0,0,0,347087,7.7750,NaN,S
813,814,0,3,"Andersson, Miss. Ebba Iris Alfrida",female,6.0,4,2,347082,31.2750,NaN,S
852,853,0,3,"Boulos, Miss. Nourelain",female,9.0,1,1,2678,15.2458,NaN,C
854,855,0,2,"Carter, Mrs. Ernest Courtenay (Lilian Hughes)",female,44.0,1,0,244252,26.0000,NaN,S

# Ramen

In [ ]:
df = pd.read_csv('/content/ramen-ratings.csv')
df_filtered = df[df.Stars!="Unrated"]
df_filtered.info()
pd.to_numeric(df_filtered['Stars'])
df_filtered

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2577 entries, 0 to 2579
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Review #  2577 non-null   int64
 1   Brand     2577 non-null   object
 2   Variety   2577 non-null   object
 3   Style     2575 non-null   object
 4   Country   2577 non-null   object
 5   Stars     2577 non-null   object
 6   Top Ten   41 non-null     object
dtypes: int64(1), object(6)
memory usage: 161.1+ KB

,Review #,Brand,Variety,Style,Country,Stars,Top Ten
0,2580,New Touch,T's Restaurant Tantanmen,Cup,Japan,3.75,NaN
1,2579,Just Way,Noodles Spicy Hot Sesame Spicy Hot Sesame Guan...,Pack,Taiwan,1,NaN
2,2578,Nissin,Cup Noodles Chicken Vegetable,Cup,USA,2.25,NaN
3,2577,Wei Lih,GGE Ramen Snack Tomato Flavor,Pack,Taiwan,2.75,NaN
4,2576,Ching's Secret,Singapore Curry,Pack,India,3.75,NaN
...,...,...,...,...,...,...,...
2575,5,Vifon,"Hu Tiu Nam Vang [""Phnom Penh"" style] Asian Sty...",Bowl,Vietnam,3.5,NaN
2576,4,Wai Wai,Oriental Style Instant Noodles,Pack,Thailand,1,NaN
2577,3,Wai Wai,Tom Yum Shrimp,Pack,Thailand,2,NaN
2578,2,Wai Wai,Tom Yum Chili Flavor,Pack,Thailand,2,NaN
2579,1,Westbrae,Miso Ramen,Pack,USA,0.5,NaN